---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: openfaas
  namespace: openfaas
  annotations:
    fluxcd.io/ignore: "false"
spec:
  releaseName: openfaas
  chart:
    repository: https://openfaas.github.io/faas-netes
    name: openfaas
    version: 5.3.7
  values:
    basic_auth: false
    exposeServices: false

    operator:
      create: true

    faasnetes:
      imagePullPolicy: "IfNotPresent"

    faasIdler:
      dryRun: false

    ingress:
      enabled: true
      hosts:
        - host: gateway.127.0.0.1.floeberg.ltd
          serviceName: gateway
          servicePort: 8080
          path: /
      annotations:
        kubernetes.io/ingress.class: nginx
