---
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: exp2csv
  namespace: openfaas-fn
spec:
  name: exp2csv
  image: registry:5000/isindir/exp2csv:0.0.2
  labels:
    com.openfaas.scale.factor: "0"
  requests:
    memory: 50Mi
    cpu: 10m
  #secrets:
  #- canister-login

