---
apiVersion: openfaas.com/v1alpha2
kind: Function
metadata:
  name: exp2csv
spec:
  name: exp2csv
  image: isindir/exp2csv:0.0.4
  labels:
    com.openfaas.scale.factor: "0"
  requests:
    memory: 50Mi
    cpu: 10m
  #secrets:
  #- canister-login

