---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: openfaas
  namespace: openfaas
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    #fluxcd.io/automated: "true"
    #fluxcd.io/tag.chart-image: semver:~3.0
spec:
  releaseName: openfaas
  chart:
    repository: https://openfaas.github.io/faas-netes
    name: openfaas
  values:
    basic_auth: false
    functionNamespace: openfaas-fn
    operator:
      create: true

