---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sops-secrets-operator
  namespace: sops
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "false"
    #fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~3.0
spec:
  releaseName: sops-secrets-operator
  chart:
    git: git@github.com:isindir/sops-secrets-operator
    ref: master
    path: chart/sops-secrets-operator
  values:
    gpg:
      enabled: true
